/**
 * Validation error codes for API responses
 * These codes should be used by Frontend for i18n translations
 */
export enum ValidationErrorCode {
  // Generic validation errors
  PROPERTY_NOT_ALLOWED = 'PROPERTY_NOT_ALLOWED',
  INVALID_TYPE = 'INVALID_TYPE',
  REQUIRED = 'REQUIRED',

  // Email validation
  EMAIL_REQUIRED = 'EMAIL_REQUIRED',
  EMAIL_INVALID = 'EMAIL_INVALID',

  // Password validation
  PASSWORD_REQUIRED = 'PASSWORD_REQUIRED',
  PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
  PASSWORD_TOO_LONG = 'PASSWORD_TOO_LONG',
  PASSWORD_INVALID_FORMAT = 'PASSWORD_INVALID_FORMAT',

  // Full Name validation
  FULL_NAME_REQUIRED = 'FULL_NAME_REQUIRED',
  FULL_NAME_INVALID_TYPE = 'FULL_NAME_INVALID_TYPE',
  FULL_NAME_TOO_SHORT = 'FULL_NAME_TOO_SHORT',
  FULL_NAME_TOO_LONG = 'FULL_NAME_TOO_LONG',
  AVATAR_INVALID_TYPE = 'AVATAR_INVALID_TYPE',
  AVATAR_TOO_LONG = 'AVATAR_TOO_LONG',

  // Auth validation
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  GOOGLE_TOKEN_INVALID = 'GOOGLE_TOKEN_INVALID',
  UNAUTHORIZED = 'UNAUTHORIZED',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  DEVICE_REQUIRED = 'DEVICE_REQUIRED',
  ACCOUNT_IN_USE_ON_ANOTHER_DEVICE = 'ACCOUNT_IN_USE_ON_ANOTHER_DEVICE',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  OAUTH_STATE_INVALID = 'OAUTH_STATE_INVALID',
  LOGIN_FORCE_REVOKE_FAILED = 'LOGIN_FORCE_REVOKE_FAILED',
  RESET_TOKEN_INVALID = 'RESET_TOKEN_INVALID',
  RESET_TOKEN_EXPIRED = 'RESET_TOKEN_EXPIRED',

  // Course validation
  COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',
  COURSE_ALREADY_EXISTS = 'COURSE_ALREADY_EXISTS',
  COURSE_NAME_REQUIRED = 'COURSE_NAME_REQUIRED',
  COURSE_DESCRIPTION_REQUIRED = 'COURSE_DESCRIPTION_REQUIRED',
  COURSE_PRICE_REQUIRED = 'COURSE_PRICE_REQUIRED',
  COURSE_STATUS_REQUIRED = 'COURSE_STATUS_REQUIRED',
  COURSE_SLUG_REQUIRED = 'COURSE_SLUG_REQUIRED',
  COURSE_AUTHOR_ID_REQUIRED = 'COURSE_AUTHOR_ID_REQUIRED',

  // Chapter validation
  CHAPTER_NOT_FOUND = 'CHAPTER_NOT_FOUND',
  CHAPTER_ALREADY_EXISTS = 'CHAPTER_ALREADY_EXISTS',
  CHAPTER_NAME_REQUIRED = 'CHAPTER_NAME_REQUIRED',
  CHAPTER_DESCRIPTION_REQUIRED = 'CHAPTER_DESCRIPTION_REQUIRED',
  CHAPTER_ORDER_REQUIRED = 'CHAPTER_ORDER_REQUIRED',
  CHAPTER_STATUS_REQUIRED = 'CHAPTER_STATUS_REQUIRED',
  CHAPTER_SLUG_REQUIRED = 'CHAPTER_SLUG_REQUIRED',
  CHAPTER_COURSE_ID_REQUIRED = 'CHAPTER_COURSE_ID_REQUIRED',

  // Lecture validation
  LECTURE_NOT_FOUND = 'LECTURE_NOT_FOUND',
  LECTURE_ALREADY_EXISTS = 'LECTURE_ALREADY_EXISTS',
  LECTURE_NAME_REQUIRED = 'LECTURE_NAME_REQUIRED',
  LECTURE_DESCRIPTION_REQUIRED = 'LECTURE_DESCRIPTION_REQUIRED',
  LECTURE_ORDER_REQUIRED = 'LECTURE_ORDER_REQUIRED',
  LECTURE_STATUS_REQUIRED = 'LECTURE_STATUS_REQUIRED',
  LECTURE_SLUG_REQUIRED = 'LECTURE_SLUG_REQUIRED',
  LECTURE_CHAPTER_ID_REQUIRED = 'LECTURE_CHAPTER_ID_REQUIRED',
  LECTURE_FILE_REQUIRED = 'LECTURE_FILE_REQUIRED',
  LECTURE_PROGRESS_NOT_FOUND = 'LECTURE_PROGRESS_NOT_FOUND',

  // Enrollment validation
  ENROLLMENT_NOT_FOUND = 'ENROLLMENT_NOT_FOUND',
  ENROLLMENT_ALREADY_EXISTS = 'ENROLLMENT_ALREADY_EXISTS',
  ENROLLMENT_PENDING_APPROVAL = 'ENROLLMENT_PENDING_APPROVAL',
  ENROLLMENT_ACCESS_DENIED = 'ENROLLMENT_ACCESS_DENIED',
  ENROLLMENT_ALREADY_REVIEWED = 'ENROLLMENT_ALREADY_REVIEWED',

  // User validation
  USER_ID_REQUIRED = 'USER_ID_REQUIRED',

  // Quiz validation
  QUIZ_NOT_FOUND = 'QUIZ_NOT_FOUND',
  QUIZ_ALREADY_EXISTS = 'QUIZ_ALREADY_EXISTS',
  QUIZ_TITLE_REQUIRED = 'QUIZ_TITLE_REQUIRED',
  QUIZ_TYPE_REQUIRED = 'QUIZ_TYPE_REQUIRED',
  QUIZ_STATUS_REQUIRED = 'QUIZ_STATUS_REQUIRED',
  QUIZ_SLUG_REQUIRED = 'QUIZ_SLUG_REQUIRED',

  // Question validation
  QUESTION_NOT_FOUND = 'QUESTION_NOT_FOUND',
  QUESTION_CONTENT_REQUIRED = 'QUESTION_CONTENT_REQUIRED',
  QUESTION_QUIZ_ID_REQUIRED = 'QUESTION_QUIZ_ID_REQUIRED',
  QUESTION_TYPE_REQUIRED = 'QUESTION_TYPE_REQUIRED',
  QUESTION_ORDER_REQUIRED = 'QUESTION_ORDER_REQUIRED',
  QUESTION_POINTS_REQUIRED = 'QUESTION_POINTS_REQUIRED',

  // Question Option validation
  OPTION_NOT_FOUND = 'OPTION_NOT_FOUND',
  OPTION_CONTENT_REQUIRED = 'OPTION_CONTENT_REQUIRED',
  OPTION_QUESTION_ID_REQUIRED = 'OPTION_QUESTION_ID_REQUIRED',
  OPTION_ORDER_REQUIRED = 'OPTION_ORDER_REQUIRED',

  // Quiz Attempt validation
  QUIZ_ATTEMPT_NOT_FOUND = 'QUIZ_ATTEMPT_NOT_FOUND',
  QUIZ_ATTEMPT_ALREADY_COMPLETED = 'QUIZ_ATTEMPT_ALREADY_COMPLETED',
  QUIZ_ATTEMPT_ACCESS_DENIED = 'QUIZ_ATTEMPT_ACCESS_DENIED',
  QUIZ_ATTEMPT_NOT_EDITABLE = 'QUIZ_ATTEMPT_NOT_EDITABLE',
  ANSWER_REQUIRED = 'ANSWER_REQUIRED',
  ANSWER_INVALID_OPTION = 'ANSWER_INVALID_OPTION',
}
